/// Flutter icons MyFlutterIcons
/// Copyright (C) 2024 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  MyFlutterIcons
///      fonts:
///       - asset: fonts/MyFlutterIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class MyFlutterIcons {
  MyFlutterIcons._();

  static const _kFontFam = 'MyFlutterIcons';
  static const String? _kFontPkg = null;

  static const IconData homeicon = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bookings = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData notification = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData user = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
